trigger:
- main 

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dockerRegistryServiceConnection: 'DockerHubConnection' # Preciso criar isso no Azure DevOps
  imageName: 'unyleya_projeto_devops:$(Build.BuildId)' # Nome da imagem Docker

steps:
- task: CmdLine@2
  inputs:
    script: 'echo Hello, world!'

# ... (outros passos aqui)

- task: Docker@2
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile' # Caminho para o Dockerfile no repositório
    buildContext: '.'
    tags: |
      $(Build.BuildId)

# ... (Qualquer outra limpeza ou passos adicionais)
