trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dockerRegistryServiceConnection: 'DockerHubConnection' # O nome da sua conexão de serviço
  imageName: 'diasnneto/unyleya:$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: 'Build and push an image to Docker Hub'
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile' # Caminho para o Dockerfile no repositório
    buildContext: '.'
    

